__BASE__: [
  '../coco.yaml',
  './hyp.scratch.m.yaml',
  './yolov12-base.yaml'
]

ms_amp_level: O3
network:
  depth_multiple: 0.50  # scales module repeats
  width_multiple: 1.00  # scales convolution channels
  max_channels: 512
  scale: m
