__BASE__: [
  '../coco.yaml',
  './hyp.scratch.l.yaml',
  './yolov12-base.yaml'
]

network:
  depth_multiple: 1  # scales module repeats
  width_multiple: 1  # scales convolution channels
  max_channels: 512
  scale: l